list_v1:
	gcc list/list_v1.c -o bin/list_v1 && ./bin/list_v1
queue_v1:
	gcc queue/queue_v1.c -o bin/queue_v1 && ./bin/queue_v1
queue_v2:
	gcc queue/queue_v2.c -o bin/queue_v2 && ./bin/queue_v2
stack_v1:
	gcc stack/stack_v1.c -o bin/stack_v1 && ./bin/stack_v1
stack_v2:
	gcc stack/stack_v2.c -o bin/stack_v2 && ./bin/stack_v2